92 - Creating Numpy Array

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

93 - Another way to create Array

In [11]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [17]:
x = np.zeros(5, dtype=int)
print(x)

[0 0 0 0 0]


94 - Logspace & Linspace

In [28]:
d = np.linspace(2,10,5, endpoint=False)
print(d)

[2.  3.6 5.2 6.8 8.4]


In [32]:
e = np.logspace(1.0, 10.0, num=10, base=2)
print(e)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


95 - Slicing Numpy Array

In [36]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14]


In [37]:
s = slice(2, 15, 2)
print(a[s])

[ 2  4  6  8 10 12 14]


In [40]:
f = a[2:15:2]
print(f)

[ 2  4  6  8 10 12 14]


In [43]:
print(a[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [45]:
print(a[:2])

[0 1]


In [51]:
a = np.arange(27)
b = a.reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
print(b[1:])

[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


96 - Advanced Indexing & Slicing Techniques

In [68]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
c = a[[0,1,1],[1,0,1]]
print(c)

[2 4 5]


In [71]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
row = np.array([[0,0],[2,2]])
cols = np.array([[1,2],[1,2]])
y = x[row,cols]
print(y)

[[1 2]
 [7 8]]


In [74]:
print(x[x>5])

[6 7 8]


97 - Broadcasting

In [75]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

c = a * b

print(c)

[ 10  40  90 160]


In [77]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [78]:
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


98 - Iterating using nditer

In [80]:
a = np.arange(0,20,2)
a = a.reshape(2,5)
print(a)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [81]:
for x in np.nditer(a):
    print(x)

0
2
4
6
8
10
12
14
16
18
